name: pmateus
favicon: null
layout_spectrum: 0.604166014585644
typography_spectrum: 0.017283045453950763
title: Pedro Mateus - Sound Engineer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7970659558195621
  lightness: 0.6475708954967558
  saturation: 0.2277155607007444
  rhythmicContrast: 0.06890907068736851
purpose: []
