name: pmateus
favicon: null
layout_spectrum: 0.51585
typography_spectrum: 0.017283045453950763
title: Pedro Mateus - Sound Engineer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#383838'
    - '#616161'
    - '#a2a2a2'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
